In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
data=pd.read_csv('horse.csv')

In [6]:
data

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0        no  adult           530101         38.5   66.0              28.0   
1       yes  adult           534817         39.2   88.0              20.0   
2        no  adult           530334         38.3   40.0              24.0   
3       yes  young          5290409         39.1  164.0              84.0   
4        no  adult           530255         37.3  104.0              35.0   
..      ...    ...              ...          ...    ...               ...   
294     yes  adult           533886          NaN  120.0              70.0   
295      no  adult           527702         37.2   72.0              24.0   
296     yes  adult           529386         37.5   72.0              30.0   
297     yes  adult           530612         36.5  100.0              24.0   
298     yes  adult           534618         37.2   40.0              20.0   

    temp_of_extremities peripheral_pulse mucous_membrane  \
0                  cool          reduced             NaN   
1                   NaN              NaN   pale_cyanotic   
2                normal           normal       pale_pink   
3                  cold           normal   dark_cyanotic   
4                   NaN              NaN   dark_cyanotic   
..                  ...              ...             ...   
294                cold              NaN   pale_cyanotic   
295                cool        increased   pale_cyanotic   
296                cold          reduced   pale_cyanotic   
297                cool          reduced       pale_pink   
298                 NaN              NaN             NaN   

    capillary_refill_time  ... packed_cell_volume total_protein  \
0              more_3_sec  ...               45.0           8.4   
1              less_3_sec  ...               50.0          85.0   
2              less_3_sec  ...               33.0           6.7   
3              more_3_sec  ...               48.0           7.2   
4              more_3_sec  ...               74.0           7.4   
..                    ...  ...                ...           ...   
294            more_3_sec  ...               55.0          65.0   
295            more_3_sec  ...               44.0           NaN   
296            less_3_sec  ...               60.0           6.8   
297            less_3_sec  ...               50.0           6.0   
298                   NaN  ...               36.0          62.0   

    abdomo_appearance abdomo_protein     outcome  surgical_lesion lesion_1  \
0                 NaN            NaN        died               no    11300   
1              cloudy            2.0  euthanized               no     2208   
2                 NaN            NaN       lived               no        0   
3       serosanguious            5.3        died              yes     2208   
4                 NaN            NaN        died               no     4300   
..                ...            ...         ...              ...      ...   
294               NaN            NaN  euthanized               no     3205   
295     serosanguious            3.3  euthanized              yes     2208   
296               NaN            NaN        died              yes     3205   
297     serosanguious            3.4       lived              yes     2208   
298             clear            1.0  euthanized               no     6112   

    lesion_2  lesion_3  cp_data  
0          0         0       no  
1          0         0       no  
2          0         0      yes  
3          0         0      yes  
4          0         0       no  
..       ...       ...      ...  
294        0         0       no  
295        0         0      yes  
296        0         0       no  
297        0         0      yes  
298        0         0       no  

[299 rows x 28 columns]

In [9]:
features=data.drop(['outcome'],axis=1)

In [10]:
target=data['outcome']

In [11]:
features

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0        no  adult           530101         38.5   66.0              28.0   
1       yes  adult           534817         39.2   88.0              20.0   
2        no  adult           530334         38.3   40.0              24.0   
3       yes  young          5290409         39.1  164.0              84.0   
4        no  adult           530255         37.3  104.0              35.0   
..      ...    ...              ...          ...    ...               ...   
294     yes  adult           533886          NaN  120.0              70.0   
295      no  adult           527702         37.2   72.0              24.0   
296     yes  adult           529386         37.5   72.0              30.0   
297     yes  adult           530612         36.5  100.0              24.0   
298     yes  adult           534618         37.2   40.0              20.0   

    temp_of_extremities peripheral_pulse mucous_membrane  \
0                  cool          reduced             NaN   
1                   NaN              NaN   pale_cyanotic   
2                normal           normal       pale_pink   
3                  cold           normal   dark_cyanotic   
4                   NaN              NaN   dark_cyanotic   
..                  ...              ...             ...   
294                cold              NaN   pale_cyanotic   
295                cool        increased   pale_cyanotic   
296                cold          reduced   pale_cyanotic   
297                cool          reduced       pale_pink   
298                 NaN              NaN             NaN   

    capillary_refill_time  ...        abdomen packed_cell_volume  \
0              more_3_sec  ...  distend_large               45.0   
1              less_3_sec  ...          other               50.0   
2              less_3_sec  ...         normal               33.0   
3              more_3_sec  ...            NaN               48.0   
4              more_3_sec  ...            NaN               74.0   
..                    ...  ...            ...                ...   
294            more_3_sec  ...  distend_large               55.0   
295            more_3_sec  ...  distend_small               44.0   
296            less_3_sec  ...  distend_large               60.0   
297            less_3_sec  ...  distend_small               50.0   
298                   NaN  ...         normal               36.0   

    total_protein abdomo_appearance abdomo_protein  surgical_lesion lesion_1  \
0             8.4               NaN            NaN               no    11300   
1            85.0            cloudy            2.0               no     2208   
2             6.7               NaN            NaN               no        0   
3             7.2     serosanguious            5.3              yes     2208   
4             7.4               NaN            NaN               no     4300   
..            ...               ...            ...              ...      ...   
294          65.0               NaN            NaN               no     3205   
295           NaN     serosanguious            3.3              yes     2208   
296           6.8               NaN            NaN              yes     3205   
297           6.0     serosanguious            3.4              yes     2208   
298          62.0             clear            1.0               no     6112   

    lesion_2  lesion_3  cp_data  
0          0         0       no  
1          0         0       no  
2          0         0      yes  
3          0         0      yes  
4          0         0       no  
..       ...       ...      ...  
294        0         0       no  
295        0         0      yes  
296        0         0       no  
297        0         0      yes  
298        0         0       no  

[299 rows x 27 columns]

In [12]:
target

0            died
1      euthanized
2           lived
3            died
4            died
          ...    
294    euthanized
295    euthanized
296          died
297         lived
298    euthanized
Name: outcome, Length: 299, dtype: object

In [17]:
features=pd.get_dummies(features)

In [18]:
features

hospital_number  rectal_temp  pulse  respiratory_rate  \
0             530101         38.5   66.0              28.0   
1             534817         39.2   88.0              20.0   
2             530334         38.3   40.0              24.0   
3            5290409         39.1  164.0              84.0   
4             530255         37.3  104.0              35.0   
..               ...          ...    ...               ...   
294           533886          NaN  120.0              70.0   
295           527702         37.2   72.0              24.0   
296           529386         37.5   72.0              30.0   
297           530612         36.5  100.0              24.0   
298           534618         37.2   40.0              20.0   

     nasogastric_reflux_ph  packed_cell_volume  total_protein  abdomo_protein  \
0                      NaN                45.0            8.4             NaN   
1                      NaN                50.0           85.0             2.0   
2                      NaN                33.0            6.7             NaN   
3                      5.0                48.0            7.2             5.3   
4                      NaN                74.0            7.4             NaN   
..                     ...                 ...            ...             ...   
294                    NaN                55.0           65.0             NaN   
295                    NaN                44.0            NaN             3.3   
296                    NaN                60.0            6.8             NaN   
297                    NaN                50.0            6.0             3.4   
298                    NaN                36.0           62.0             1.0   

     lesion_1  lesion_2  ...  abdomen_firm  abdomen_normal  abdomen_other  \
0       11300         0  ...             0               0              0   
1        2208         0  ...             0               0              1   
2           0         0  ...             0               1              0   
3        2208         0  ...             0               0              0   
4        4300         0  ...             0               0              0   
..        ...       ...  ...           ...             ...            ...   
294      3205         0  ...             0               0              0   
295      2208         0  ...             0               0              0   
296      3205         0  ...             0               0              0   
297      2208         0  ...             0               0              0   
298      6112         0  ...             0               1              0   

     abdomo_appearance_clear  abdomo_appearance_cloudy  \
0                          0                         0   
1                          0                         1   
2                          0                         0   
3                          0                         0   
4                          0                         0   
..                       ...                       ...   
294                        0                         0   
295                        0                         0   
296                        0                         0   
297                        0                         0   
298                        1                         0   

     abdomo_appearance_serosanguious  surgical_lesion_no  surgical_lesion_yes  \
0                                  0                   1                    0   
1                                  0                   1                    0   
2                                  0                   1                    0   
3                                  1                   0                    1   
4                                  0                   1                    0   
..                               ...                 ...                  ...   
294                                0                   1                    0   
295              

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(features,target,random_state=10)

In [28]:
x_train.shape

(224, 67)

In [29]:
x_test.shape

(75, 67)

In [34]:
x_train.isnull().sum()

hospital_number                      0
rectal_temp                         45
pulse                               19
respiratory_rate                    45
nasogastric_reflux_ph              182
                                  ... 
abdomo_appearance_serosanguious      0
surgical_lesion_no                   0
surgical_lesion_yes                  0
cp_data_no                           0
cp_data_yes                          0
Length: 67, dtype: int64

In [30]:
from sklearn.impute import SimpleImputer

In [31]:
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [32]:
imputer

SimpleImputer(strategy='most_frequent')

In [35]:
x_train=imputer.fit_transform(x_train)
x_test=imputer.fit_transform(x_test)

In [47]:
pd.DataFrame(x_train).isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
62    0
63    0
64    0
65    0
66    0
Length: 67, dtype: int64

In [49]:
from sklearn.naive_bayes import BernoulliNB

In [50]:
nb_model=BernoulliNB()

In [51]:
nb_model.fit(x_train,y_train)

BernoulliNB()

In [52]:
y_predict=nb_model.predict(x_test)

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [54]:
print(accuracy_score(y_predict,y_test))

0.6


In [55]:
print(confusion_matrix(y_predict,y_test))

[[ 9  3 16]
 [ 1  3  0]
 [ 5  5 33]]


In [56]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

        died       0.60      0.32      0.42        28
  euthanized       0.27      0.75      0.40         4
       lived       0.67      0.77      0.72        43

    accuracy                           0.60        75
   macro avg       0.52      0.61      0.51        75
weighted avg       0.62      0.60      0.59        75

